services:
  db:
    image: postgres:latest
    ports:
      - "5543:5432"
    restart: always
    environment:
      POSTGRES_USER: zero-waste-user
      POSTGRES_PASSWORD: zero-waste-password
      POSTGRES_DB: zero-waste-db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
