@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@api = api/v1
@accessToken =eyJhbGciOiJIUzM4NCJ9.eyJpZCI6IjQ3MGQ2YzRhLWFhMWMtNDJmMS05MjRlLWJhYzBjMjc1ZWRlNCIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX0FETUlOIn0seyJhdXRob3JpdHkiOiJST0xFX1VTRVIifV0sInN1YiI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNzc1MzE2NzQ1LCJleHAiOjE3NzUzMTc2NDV9.ABlGZ4BVg3j_AhXEwR4yUls8RowxA0oHmeSv0TMgHJNz1kYHWeUsLR29lKWe6M9U
### AUTH
POST http://{{host}}/{{api}}/auth/register
Content-Type: application/json

{
    "firstName":"John",
    "lastName":"Doe",
    "location":"Texas",
    "phoneNumber":"23912123",
    "email": "john.doe@example.com",
    "password": "SecurePassword123!"
}
###

POST http://{{host}}/{{api}}/auth/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "SecurePassword123!"
}

###
POST http://{{host}}/{{api}}/auth/refresh
Content-Type: application/json

### USERS
GET http://{{host}}/{{api}}/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
