@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@api = api/v1
@accessToken =eyJhbGciOiJIUzM4NCJ9.eyJpZCI6ImU1NDVmNzFhLTFkNWQtNDM2Yi05NWM4LTBjMzVjNzMwNjYyMCIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifV0sInN1YiI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNzc1NDgwMTczLCJleHAiOjE3NzU0ODEwNzN9.oJYK-PgkB-y7IB06veL5LRwlzNDujPNgMFVS_UPMdwb481m3iWH92CHPV1qLzNiC

### AUTH
POST http://{{host}}/{{api}}/auth/register
Content-Type: application/json

{
    "firstName":"John",
    "lastName":"Doe",
    "city":"Texas",
    "phoneNumber":"23912123",
    "email": "john.doe@example.com",
    "password": "SecurePassword123!"
}
###

POST http://{{host}}/{{api}}/auth/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "SecurePassword123!"
}

###
POST http://{{host}}/{{api}}/auth/refresh

###
GET http://{{host}}/{{api}}/auth/me
Authorization: Bearer {{accessToken}}

### USERS
GET http://{{host}}/{{api}}/users
Authorization: Bearer {{accessToken}}


### items
GET http://{{host}}/{{api}}/items/skldjsdl
