CREATE TABLE IF NOT EXISTS event_publication
(
  id                     UUID NOT NULL,
  listener_id            TEXT NOT NULL,
  event_type             TEXT NOT NULL,
  serialized_event       TEXT NOT NULL,
  publication_date       TIMESTAMP WITH TIME ZONE NOT NULL,
  completion_date        TIMESTAMP WITH TIME ZONE,
  status                 TEXT,
  completion_attempts    INT,
  last_resubmission_date TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS event_publication_serialized_event_hash_idx ON event_publication USING hash(serialized_event);
CREATE INDEX IF NOT EXISTS event_publication_by_completion_date_idx ON event_publication (completion_date);

CREATE TABLE IF NOT EXISTS event_publication_archive
(
  id                     UUID NOT NULL,
  listener_id            TEXT NOT NULL,
  event_type             TEXT NOT NULL,
  serialized_event       TEXT NOT NULL,
  publication_date       TIMESTAMP WITH TIME ZONE NOT NULL,
  completion_date        TIMESTAMP WITH TIME ZONE,
  status                 TEXT,
  completion_attempts    INT,
  last_resubmission_date TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS event_publication_archive_serialized_event_hash_idx ON event_publication_archive USING hash(serialized_event);
CREATE INDEX IF NOT EXISTS event_publication_archive_by_completion_date_idx ON event_publication_archive (completion_date);

CREATE TABLE users (
    id UUID NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    ban_active BOOLEAN NOT NULL,
    banned_until TIMESTAMP WITH TIME ZONE,
    role VARCHAR(50) NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);


CREATE TABLE oauth_accounts (
    id UUID NOT NULL,
    user_id UUID NOT NULL,
    provider VARCHAR(50) NOT NULL,
    provider_id VARCHAR(255) NOT NULL,

    CONSTRAINT pk_oauth_accounts PRIMARY KEY (id),
    CONSTRAINT uk_oauth_provider_user UNIQUE (provider, provider_id),
    CONSTRAINT fk_oauth_account_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    token VARCHAR(255) NOT NULL,
    user_id UUID NOT NULL,
    expiry_date TIMESTAMP WITH TIME ZONE,
    revoked BOOLEAN NOT NULL,

    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uk_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE TABLE categories (
    id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    parent_id UUID,

    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uk_categories_name UNIQUE (name),
    CONSTRAINT fk_category_parent
        FOREIGN KEY (parent_id)
        REFERENCES categories(id)
        ON DELETE SET NULL
);


CREATE TABLE items (
    id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    condition VARCHAR(50) NOT NULL,
    state VARCHAR(50) NOT NULL,
    category_id UUID NOT NULL,
    owner_id UUID NOT NULL,

    thumbnail_id UUID,

    moderation_status VARCHAR(50) NOT NULL,
    moderated_at TIMESTAMP WITH TIME ZONE,
    moderated_by UUID,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_items PRIMARY KEY (id),

    CONSTRAINT fk_item_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id),

    CONSTRAINT fk_item_owner
        FOREIGN KEY (owner_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE TABLE item_images (
    item_id UUID NOT NULL,
    image_id UUID,
    image_order INTEGER NOT NULL,

    CONSTRAINT pk_item_images PRIMARY KEY (item_id, image_order),

    CONSTRAINT fk_item_images_item
        FOREIGN KEY (item_id)
        REFERENCES items(id)
        ON DELETE CASCADE
);


CREATE TABLE images (
    id UUID NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    size BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    item_id UUID NOT NULL,

    CONSTRAINT pk_images PRIMARY KEY (id),

    CONSTRAINT fk_image_item
        FOREIGN KEY (item_id)
        REFERENCES items(id)
        ON DELETE CASCADE
);


CREATE TABLE offers (
    id UUID NOT NULL,
    buyer_id UUID NOT NULL,
    item_id UUID NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_offers PRIMARY KEY (id),

    CONSTRAINT uk_offer_buyer_item
        UNIQUE (buyer_id, item_id),

    CONSTRAINT fk_offer_buyer
        FOREIGN KEY (buyer_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_offer_item
        FOREIGN KEY (item_id)
        REFERENCES items(id)
        ON DELETE CASCADE
);


CREATE TABLE reviews (
    id UUID NOT NULL,
    description TEXT,
    rating INTEGER NOT NULL,
    offer_id UUID NOT NULL,
    reviewer_id UUID NOT NULL,
    reviewee_id UUID NOT NULL,

    moderation_status VARCHAR(50) NOT NULL,
    moderated_at TIMESTAMP WITH TIME ZONE,
    moderated_by UUID,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_reviews PRIMARY KEY (id),

    CONSTRAINT fk_review_offer
        FOREIGN KEY (offer_id)
        REFERENCES offers(id),

    CONSTRAINT fk_review_reviewer
        FOREIGN KEY (reviewer_id)
        REFERENCES users(id),

    CONSTRAINT fk_review_reviewee
        FOREIGN KEY (reviewee_id)
        REFERENCES users(id)
);


CREATE TABLE notifications (
    id UUID NOT NULL,
    recipient_id UUID NOT NULL,
    notification_type VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(255) NOT NULL,
    read BOOLEAN NOT NULL,
    reference_id UUID NOT NULL,
    reference_type VARCHAR(100) NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_notifications PRIMARY KEY (id),

    CONSTRAINT fk_notification_recipient
        FOREIGN KEY (recipient_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE TABLE reports (
    id UUID NOT NULL,
    reporter_id UUID NOT NULL,
    subject_type VARCHAR(50) NOT NULL,
    subject_id UUID NOT NULL,
    reason VARCHAR(100) NOT NULL,
    comment TEXT,
    status VARCHAR(50) NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    resolved_by UUID,
    admin_note TEXT,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_reports PRIMARY KEY (id),

    CONSTRAINT fk_report_reporter
        FOREIGN KEY (reporter_id)
        REFERENCES users(id)
);


CREATE TABLE user_bans (
    id UUID NOT NULL,
    user_id UUID NOT NULL,
    reason VARCHAR(255) NOT NULL,
    banned_by UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    revoked_by UUID,
    revoked_reason VARCHAR(255),

    CONSTRAINT pk_user_bans PRIMARY KEY (id),

    CONSTRAINT fk_user_ban_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_ban_banned_by
        FOREIGN KEY (banned_by)
        REFERENCES users(id)
);


CREATE TABLE blogs (
    id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    author_id UUID,

    moderation_status VARCHAR(50) NOT NULL,
    moderated_at TIMESTAMP WITH TIME ZONE,
    moderated_by UUID,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_blogs PRIMARY KEY (id),

    CONSTRAINT fk_blog_author
        FOREIGN KEY (author_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);
